<?xml version="1.0" encoding="UTF-8"?>

<!--
   Copyright 2024-2026 the original author or authors.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

        https://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
-->

<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xmlns="http://maven.apache.org/POM/4.0.0"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

	<modelVersion>4.0.0</modelVersion>
	<groupId>com.coderlee.ai</groupId>
	<artifactId>springai-alibaba-learn</artifactId>
	<version>${revision}</version>
	<packaging>pom</packaging>
	<modules>
		<module>saa_01_helloworld</module>
		<module>saa_02_ollama</module>
		<module>saa_03_chatmodelchatclient</module>
		<module>saa_04_streamingoutput</module>
		<module>saa_05_prompt</module>
		<module>saa_06_prompt_template</module>
		<module>saa_07_structured_output</module>
		<module>saa_08_persistent</module>
		<module>saa_09_text2image</module>
		<module>saa_10_text2voice</module>
		<module>saa_11_embed2vector</module>
		<module>saa_12_rag4aiops</module>
		<module>saa_13_toolcalling</module>
		<module>saa_14_local_mcpserver</module>
		<module>saa_14_local_mcpclient</module>
		<module>saa_15_mcpclient_4_baidumap_mcserver</module>
		<module>saa_16_bailianrag</module>
		<module>saa_17_todaymenu</module>
	</modules>

	<description>Spring AI Alibaba Learn</description>
	<name>Spring AI Alibaba Learn</name>
	<url>https://github.com/lehedrn/springai-alibaba-learn</url>

	<properties>
		<!-- Project revision -->
		<revision>1.0.0</revision>

		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<java.version>17</java.version>
		<maven.compiler.source>17</maven.compiler.source>
		<maven.compiler.target>17</maven.compiler.target>

		<!-- Spring AI -->
		<spring-ai.version>1.0.0</spring-ai.version>

		<!-- Spring AI Alibaba -->
		<!-- Install Spring AI Alibaba in your local. -->
		<spring-ai-alibaba.version>1.0.0.2</spring-ai-alibaba.version>

		<!-- Spring Boot -->
		<spring-boot.version>3.4.5</spring-boot.version>

		<!-- maven plugin -->
		<maven-deploy-plugin.version>3.1.1</maven-deploy-plugin.version>
		<flatten-maven-plugin.version>1.3.0</flatten-maven-plugin.version>
		<maven-compiler-plugin.version>3.8.1</maven-compiler-plugin.version>
	</properties>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-dependencies</artifactId>
				<version>${spring-boot.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
			<dependency>
				<groupId>org.springframework.ai</groupId>
				<artifactId>spring-ai-bom</artifactId>
				<version>${spring-ai.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
			<dependency>
				<groupId>com.alibaba.cloud.ai</groupId>
				<artifactId>spring-ai-alibaba-bom</artifactId>
				<version>${spring-ai-alibaba.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
			
		</dependencies>
	</dependencyManagement>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<version>${spring-boot.version}</version>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-deploy-plugin</artifactId>
				<version>${maven-deploy-plugin.version}</version>
				<configuration>
					<skip>true</skip>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>${maven-compiler-plugin.version}</version>
				<configuration>
					<release>${java.version}</release>
					<compilerArgs>
						<compilerArg>-parameters</compilerArg>
					</compilerArgs>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>flatten-maven-plugin</artifactId>
				<version>${flatten-maven-plugin.version}</version>
				<inherited>true</inherited>
				<executions>
					<execution>
						<id>flatten</id>
						<phase>process-resources</phase>
						<goals>
							<goal>flatten</goal>
						</goals>
						<configuration>
							<updatePomFile>true</updatePomFile>
							<flattenMode>ossrh</flattenMode>
							<pomElements>
								<distributionManagement>remove</distributionManagement>
								<dependencyManagement>remove</dependencyManagement>
								<repositories>remove</repositories>
								<scm>keep</scm>
								<url>keep</url>
								<organization>resolve</organization>
							</pomElements>
						</configuration>
					</execution>
					<execution>
						<id>flatten.clean</id>
						<phase>clean</phase>
						<goals>
							<goal>clean</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>

</project>
