server:
  port: 18080
  servlet:
    encoding:
      enabled: true
      force: true
      charset: UTF-8

spring:
  application:
    name: saa_16_bailianrag
  ai:
    dashscope:
      api-key: ${DASHSCOPE_API}
      workspace-id: llm-8srbgjnfh29rqpyb