server:
  port: 18080
  servlet:
    encoding:
      enabled: true
      force: true
      charset: UTF-8

spring:
  application:
    name: saa_07_structured_output
  ai:
    dashscope:
      api-key: ${DASHSCOPE_API}